### ISSUE TITLE
Migration to Weblate | Tracking issue

### ISSUE THREAD

**Issue by erciccione** [monero-ecosystem/monero-translations#63]
This is what's left of a todo file i had created to keep track of what needs to be done about the migration to weblate. Leaving it here so that others can make suggestions for improvements if they feel like it. I will update it.

This points are created according to [my CCS proposal](https://repo.getmonero.org/monero-project/ccs-proposals/merge_requests/94).

- [x] Import terminology guides (convert them in suitable format first)
	- [ ] Remove terminology guides from GitHub (?)
- [x] Import unpushed contributions from Pootle
- [x] Import Dutch translation memory
- [x] Test email service
- [x] Define revision process
- [x] Fix problem of translations for CLI made in pootle but not committed (wait for moneromoo's patch to activate languages)
- [x] Possibility to log in with github and gitlab
- [x] Create scheduled database dump and weekly backup. (discussed with pigeons)
- [x] Create guide (substitute pootle's) and link it from weblate
- [ ] Commits are squashed before being pushed upstream with a PR. Should the body of the commit be edited to give credits to translators or would be enough to provide the list of contributors before the release?

**Comment by el00ruobuob** [comment]
`Should the body of the commit be edited to give credits to translators or would...` => IMO yes, but this may be tricky as it suppose to identify Weblate users' corresponding github accounts (unless i missed something).

**Comment by erciccione** [comment]
The problem is that we cannot push a commit for every author or the pony and luigi would kill me, so the commits are squashed by languages. The problem is that that way they don't give attribution to the author and i don't want that commit to be messed up with a lot of names in the description. I'll se what's possible wth the templates Django offers first, if it's not doable i will just make a dump of the translators from Django and post it in the PR (that's what i used to do with Pootle)

**Comment by el00ruobuob** [comment]
Maybe limit each commit message with top-3 contributors as co-authors? Would that be acceptable?

**Comment by erciccione** [comment]
The migration is complete and all points completed (except the last one about credit contributors, but it's minor and can be solved in a number of ways0). The terminology guides will stay on this repository, since additions/removals from the glossaries should be discussed first.

Closing this issue.
